In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np

In [2]:
partial_sudokus = pd.read_csv('/home/lilly/Studies/ANN/partial_sudokus.csv')
partial_sudokus

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
0,0,8,3,2,3,5,4,1,7,0,...,3,0,0,0,0,1,0,0,0,8
1,1,0,0,7,5,4,0,3,2,0,...,4,4,0,3,6,2,8,1,8,0
2,3,0,0,0,5,0,8,3,9,8,...,2,5,8,6,0,0,0,0,0,7
3,0,0,0,0,9,3,0,0,7,8,...,4,4,0,0,2,1,8,0,5,6
4,6,8,0,7,3,0,0,9,0,8,...,0,7,4,0,8,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0,8,9,6,0,0,0,5,7,6,...,0,8,6,0,3,0,0,7,1,5
49996,7,4,1,3,0,9,0,0,8,0,...,9,4,9,0,0,0,5,0,1,0
49997,2,0,0,4,8,3,9,1,0,1,...,0,0,0,6,5,0,2,0,5,4
49998,9,0,8,2,0,0,0,0,0,0,...,2,0,9,0,1,7,0,0,0,0
49999,3,1,6,4,2,3,9,0,5,0,...,3,2,0,1,0,0,0,6,3,9

In [3]:
filled_sudokus = pd.read_csv('/home/lilly/Studies/ANN/filled_sudokus.csv')
filled_sudokus

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
0,8,8,3,2,9,5,4,1,7,4,...,1,2,5,7,9,1,3,4,4,8
1,1,6,9,7,5,4,8,3,2,3,...,4,4,9,7,6,2,5,1,8,3
2,7,1,2,6,5,4,8,3,9,8,...,2,5,8,6,2,4,9,3,1,7
3,2,7,4,5,9,3,6,8,7,8,...,4,4,9,7,2,1,8,3,5,2
4,6,5,2,7,3,4,8,9,1,3,...,9,7,4,6,8,8,9,3,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,8,9,5,2,4,3,5,7,6,...,2,8,6,4,3,9,2,7,1,5
49996,7,4,1,3,5,9,2,6,8,9,...,9,4,9,3,8,6,5,7,1,2
49997,2,5,7,4,6,3,9,1,8,1,...,9,8,9,6,3,7,2,1,5,4
49998,9,3,8,2,5,7,1,4,6,1,...,2,2,9,6,8,7,8,4,3,5
49999,7,1,6,4,2,3,9,8,5,5,...,7,2,4,1,8,7,5,6,3,9

In [4]:
train_sudokus = pd.DataFrame({
    'partialsudokus': partial_sudokus.apply(lambda row: (''.join(map(str, row))), axis=1),
    'filledsudokus': filled_sudokus.apply(lambda row: (''.join(map(str, row))), axis=1)
})

train_sudokus

,partialsudokus,filledsudokus
0,0832354170018000590350008620700009000000700203...,8832954174218673597953418625721349868465791233...
1,1007540320002060070048390500070780000405903100...,1697548323582169472748396515314782967465923189...
2,3000508398000230409300782002798004000004970266...,7126548398659237419342782652798614533584871266...
3,0000930078030000290590824039003502036001007088...,2745936878637415297596824139783542616351297481...
4,6807300908986000070370002560003456020000080742...,6527348913986524374371982569713456823852619742...
...,...,...
49995,0896000576200008000408102060107098239020800000...,1895243576279351845438172964167598239724835613...
49996,7413090080050800402300000708000360276570481903...,7413592689657823412386149757895364276572488933...
49997,2004839101040080000800057034200030080008064979...,2574639181347986256892157438219573863758264919...
49998,9082000000024609706748000507000193800000025003...,9382571461524639786748912537256193844593825173...
49999,3164239050240080000390060200026800730970040004...,7164239855247983168391567241586894733972145684...

In [5]:
train_sudokus.to_csv('./train_sudokus.csv')

In [6]:
test_sudokus = pd.read_csv('/home/lilly/Studies/ANN/test_sudokus.csv')
test_sudokus

,0,1,2,3,4,5,6,7,8,9,...,71,72,73,74,75,76,77,78,79,80
0,2,0,7,0,1,3,4,0,0,8,...,0,4,0,2,0,8,0,3,0,0
1,0,0,2,0,8,0,0,4,7,0,...,0,0,8,6,0,7,0,5,0,0
2,0,0,0,0,4,6,3,0,0,4,...,5,0,4,5,0,6,0,0,7,0
3,0,0,4,5,0,0,0,0,6,1,...,7,0,7,3,4,0,0,2,0,0
4,0,0,8,0,0,3,0,0,0,0,...,8,1,0,0,8,4,7,9,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,3,0,1,0,0,2,7,8,0,0,...,9,0,1,2,0,0,8,5,0,0
9996,0,0,0,0,7,2,6,0,9,0,...,0,5,0,0,0,2,0,0,0,0
9997,8,8,7,5,0,0,0,0,3,0,...,0,3,6,8,0,0,0,0,4,1
9998,7,0,0,4,1,0,0,9,8,0,...,0,0,7,2,0,0,3,4,0,0
9999,0,4,0,1,5,2,0,6,0,0,...,5,0,8,6,4,3,5,2,0,9

In [7]:
test_sudokus = pd.DataFrame({
    'partialsudokus': test_sudokus.apply(lambda row: (''.join(map(str, row))), axis=1),
})

test_sudokus

                                         partialsudokus
0     2070134008060482359030068000900500201084705600...
1     0020800470041007088078060032607000007052000163...
2     0000463004009137560530280090040070020806000400...
3     0045000061078634002000405803096847007059306100...
4     0080030000009203063005007200081026500020090006...
...                                                 ...
9995  3010027800080360700090050000004200900205798300...
9996  0000726090050800400004000500000180409002078168...
9997  8875000030000870045340862070050310009030401000...
9998  7004100980903020000280000462406000853014576040...
9999  0401520600010007000680430006003105000840640028...

[10000 rows x 1 columns]

In [8]:
data = pd.read_csv('/home/lilly/Studies/ANN/train_sudokus.csv')
data

,Unnamed: 0,partialsudokus,filledsudokus
0,0,0832354170018000590350008620700009000000700203...,8832954174218673597953418625721349868465791233...
1,1,1007540320002060070048390500070780000405903100...,1697548323582169472748396515314782967465923189...
2,2,3000508398000230409300782002798004000004970266...,7126548398659237419342782652798614533584871266...
3,3,0000930078030000290590824039003502036001007088...,2745936878637415297596824139783542616351297481...
4,4,6807300908986000070370002560003456020000080742...,6527348913986524374371982569713456823852619742...
...,...,...,...
49995,49995,0896000576200008000408102060107098239020800000...,1895243576279351845438172964167598239724835613...
49996,49996,7413090080050800402300000708000360276570481903...,7413592689657823412386149757895364276572488933...
49997,49997,2004839101040080000800057034200030080008064979...,2574639181347986256892157438219573863758264919...
49998,49998,9082000000024609706748000507000193800000025003...,9382571461524639786748912537256193844593825173...
49999,49999,3164239050240080000390060200026800730970040004...,7164239855247983168391567241586894733972145684...

In [9]:
train_sudokus = pd.DataFrame(data.iloc[:, 1:3])
train_sudokus

,partialsudokus,filledsudokus
0,0832354170018000590350008620700009000000700203...,8832954174218673597953418625721349868465791233...
1,1007540320002060070048390500070780000405903100...,1697548323582169472748396515314782967465923189...
2,3000508398000230409300782002798004000004970266...,7126548398659237419342782652798614533584871266...
3,0000930078030000290590824039003502036001007088...,2745936878637415297596824139783542616351297481...
4,6807300908986000070370002560003456020000080742...,6527348913986524374371982569713456823852619742...
...,...,...
49995,0896000576200008000408102060107098239020800000...,1895243576279351845438172964167598239724835613...
49996,7413090080050800402300000708000360276570481903...,7413592689657823412386149757895364276572488933...
49997,2004839101040080000800057034200030080008064979...,2574639181347986256892157438219573863758264919...
49998,9082000000024609706748000507000193800000025003...,9382571461524639786748912537256193844593825173...
49999,3164239050240080000390060200026800730970040004...,7164239855247983168391567241586894733972145684...

In [10]:
# Function to check length
def check_length(sudoku_str):
    return len(sudoku_str) == 81

# Applying the check_length function to each element in the specified columns
partial_lengths = data['partialsudokus'].apply(lambda x: check_length(x))
filled_lengths = data['filledsudokus'].apply(lambda x: check_length(x))

# Display the results
print("Rows with Incorrect Partial Sudokus Length:")
print(data[~partial_lengths])

print("\nRows with Incorrect Filled Sudokus Length:")
print(data[~filled_lengths])

Rows with Incorrect Partial Sudokus Length:
Empty DataFrame
Columns: [Unnamed: 0, partialsudokus, filledsudokus]
Index: []

Rows with Incorrect Filled Sudokus Length:
Empty DataFrame
Columns: [Unnamed: 0, partialsudokus, filledsudokus]
Index: []

In [11]:
class SudokuDataset(Dataset):
    def __init__(self, dataframe, subset="train"):
        self.dataframe = dataframe
        self.subset = subset

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        puzzle = self.dataframe.iloc[idx, 1]
        solution = self.dataframe.iloc[idx, 2]
        puzzle = torch.tensor([int(p) for p in str(puzzle)], dtype=torch.float32).reshape(1, 9, 9) / 9 - 0.5
        if self.subset == 'train':
            # Subtracting 1 from each solution value to match PyTorch's 0-based indexing
            #solution = torch.tensor([max(0, int(s) - 1) for s in solution], dtype=torch.int64).reshape(-1)
            solution = torch.tensor([int(s) - 1 for s in str(solution)], dtype=torch.int64).reshape(81)
            return puzzle, solution
        return puzzle
    
    # def __getitem__(self, idx):
    #     puzzle = self.dataframe.iloc[idx, 1]
    #     solution = self.dataframe.iloc[idx, 2]
    #     puzzle = torch.tensor([int(p) for p in str(puzzle)], dtype=torch.float32).reshape(1, 9, 9) / 9 - 0.5
    #     if self.subset == 'train':
    #         # Modify target representation to one-hot encode
    #         solution = torch.nn.functional.one_hot(torch.tensor([int(s) - 1 for s in str(solution)], dtype=torch.int64), num_classes=9).reshape(81, -1)
    #         return puzzle, solution
    #     return puzzle

In [12]:
train_idx = int(len(data) * 0.75)
train_data = SudokuDataset(data.iloc[:train_idx], subset="train")
train_loader = DataLoader(train_data, batch_size=640, shuffle=True)

val_data = SudokuDataset(data.iloc[train_idx:], subset="train")
val_loader = DataLoader(val_data, batch_size=640, shuffle=False)

In [13]:
def create_constraint_mask():
    constraint_mask = torch.zeros((81, 3, 81), dtype=torch.float)
    # row constraints
    for a in range(81):
        r = 9 * (a // 9)
        for b in range(9):
            constraint_mask[a, 0, r + b] = 1

    # column constraints
    for a in range(81):
        c = a % 9
        for b in range(9):
            constraint_mask[a, 1, c + 9 * b] = 1

    # box constraints
    for a in range(81):
        r = a // 9
        c = a % 9
        br = 3 * 9 * (r // 3)
        bc = 3 * (c // 3)
        for b in range(9):
            r = b % 3
            c = 9 * (b // 3)
            constraint_mask[a, 2, br + bc + r + c] = 1

    return constraint_mask

In [14]:
def create_constraint_mask():
    constraint_mask = torch.zeros((81, 3, 9), dtype=torch.float)
    # row constraints
    for a in range(81):
        r = 9 * (a // 9)
        for b in range(9):
            constraint_mask[a, 0, b] = 1 if (r + b) == (a % 9) else 0

    # column constraints
    for a in range(81):
        c = a % 9
        for b in range(9):
            constraint_mask[a, 1, b] = 1 if (c + 9 * b) == a else 0

    # box constraints
    for a in range(81):
        r = a // 9
        c = a % 9
        br = 3 * 9 * (r // 3)
        bc = 3 * (c // 3)
        for b in range(9):
            r = b % 3
            c = 9 * (b // 3)
            constraint_mask[a, 2, b] = 1 if (br + bc + r + c) == a else 0

    return constraint_mask

In [15]:
import torch.nn as nn
class ConstraintModule(nn.Module):
    def __init__(self):
        super(ConstraintModule, self).__init__()
        self.constraint_mask = create_constraint_mask()

    def forward(self, x):
        # Expand the constraint mask to match the batch size
        expanded_mask = self.constraint_mask.unsqueeze(0).expand(x.size(0), -1, -1)

        # Reshape the input x to match the constraint mask dimensions
        x_reshaped = x.view(x.size(0), -1, 1)

        # Apply the constraint mask to the input
        x = x_reshaped * expanded_mask

        # Reshape the result back to the original shape
        x = x.view(x.size(0), x.size(1), x.size(2), x.size(3))

        return x

In [16]:
import torch.nn as nn
import torch.nn.functional as F

class SudokuSolver(nn.Module):
    def __init__(self):
        super(SudokuSolver, self).__init__()
        self.conv1 = nn.Conv2d(1, 64, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 128, kernel_size=1)
        self.fc1 = nn.Linear(128 * 9 * 9, 81 * 9)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        return x.view(-1, 9)  # Reshaped to match [batch_size * 81, 9]

model = SudokuSolver()

In [17]:
import torch.nn as nn
import torch.nn.functional as F

class FastSudokuSolver(nn.Module):
    def __init__(self):
        super(FastSudokuSolver, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        
        self.fc1 = nn.Linear(64 * 9 * 9, 512)
        self.fc2 = nn.Linear(512, 81 * 9)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        
        return x.view(-1, 9)

model = FastSudokuSolver()

In [18]:
import torch.nn as nn
import torch.nn.functional as F

class SudokuSolver(nn.Module):
    def __init__(self):
        super(SudokuSolver, self).__init__()
        self.constraints = ConstraintModule()
        self.conv1 = nn.Conv2d(1, 64, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(64)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(128)
        self.conv3 = nn.Conv2d(128, 128, kernel_size=1)
        self.fc1 = nn.Linear(128 * 9 * 9, 81 * 9)
        
    # def forward(self, x):
    #     x = self.constraints(x)
        
    #     x = F.relu(self.bn1(self.conv1(x)))
    #     x = F.relu(self.bn2(self.conv2(x)))
    #     x = F.relu(self.conv3(x))
    #     x = x.view(x.size(0), -1)
    #     x = self.fc1(x)
        
    #     return x.view(-1, 9)


    def forward(self, x):
        expanded_mask = self.constraints(x)
        x = x * expanded_mask
        
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(x.size(0), -1)
        x = self.fc1(x)
        
        return x.view(-1, 9)
    
    # def forward(self, x):
    #     x = self.constraints(x)
    #     x = F.relu(self.bn1(self.conv1(x)))
    #     x = F.relu(self.bn2(self.conv2(x)))
    #     x = F.relu(self.conv3(x))
    #     x = x.view(x.size(0), -1)
    #     x = self.fc1(x)
    #     x = x.view(-1, 9)  # Reshaped to match [batch_size * 81, 9]
    #     constraint_mask = self.constraint_mask.unsqueeze(0).expand(x.size(0), -1, -1)
    #     # Apply the constraint mask to the output
    #     x = x * constraint_mask
    #     return x # Reshaped to match [batch_size * 81, 9]

model = SudokuSolver()

In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

In [20]:
def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, dim=1)
    correct = (predicted == labels).sum().item()
    return correct / labels.size(0)

def train_model(model, train_loader, val_loader, epochs):
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        train_correct = 0
        total_train = 0
        # Training Phase
        for puzzles, solutions in train_loader:
            puzzles, solutions = puzzles.to(device), solutions.to(device)
            optimizer.zero_grad()
            #print(puzzles.size())
            outputs = model(puzzles)
            # print('outputs :', outputs.shape)
            # print('sols :', solutions.view(-1).shape)
            loss = criterion(outputs, solutions.view(-1))
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            train_correct += calculate_accuracy(outputs, solutions.view(-1)) * solutions.size(0)
            total_train += solutions.size(0)

        avg_train_loss = train_loss / len(train_loader)
        train_accuracy = train_correct / total_train
        # Validation Phase
        model.eval()
        val_loss = 0.0
        val_correct = 0
        total_val = 0

        with torch.no_grad():
            for puzzles, solutions in val_loader:
                puzzles, solutions = puzzles.to(device), solutions.to(device)
                outputs = model(puzzles)
                val_loss += criterion(outputs, solutions.view(-1)).item()

                val_correct += calculate_accuracy(outputs, solutions.view(-1)) * solutions.size(0)
                total_val += solutions.size(0)

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = val_correct / total_val

        print(f'Epoch {epoch + 1}: '
              f'Train Loss: {avg_train_loss:.4f}, '
              f'Train Accuracy: {train_accuracy:.4f}, '
              f'Validation Loss: {avg_val_loss:.4f}, '
              f'Validation Accuracy: {val_accuracy:.4f}')

In [21]:
train_model(model, train_loader, val_loader, 12)

RuntimeError: expand(torch.FloatTensor{[1, 81, 3, 9]}, size=[640, -1, -1]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)

In [ ]:
import pandas as pd
test=pd.read_csv('/home/lilly/Studies/ANN/test_sudokus.csv')
test_sudokus = pd.DataFrame({
    'partialsudokus': test.apply(lambda row: (''.join(map(str, row))), axis=1),
})

test_sudokus

                                         partialsudokus
0     4027008637614000250800000706070950007106000542...
1     0708010200207700001060920040900754800420080038...
2     0009001650806000306012437008070950230307046009...
3     1580096070000760027264183000157040000040800570...
4     0020500096038002059700008361080005032060550800...
...                                                 ...
9995  0001050300407062100009405607510943060802507040...
9996  1058000404001300056030509170006009315060030092...
9997  0000278000703000900484500367800000040924009783...
9998  0070450000391800001050020980017200803275009164...
9999  0463518299308020000109005304730900005600300800...

[10000 rows x 1 columns]

In [ ]:
# Function to check length
def check_length(sudoku_str):
    return len(sudoku_str) == 81

# Applying the check_length function to each element in the specified columns
partial_lengths = data['partialsudokus'].apply(lambda x: check_length(x))

# Display the results
print("Rows with Incorrect Partial Sudokus Length:")
print(data[~partial_lengths])

Rows with Incorrect Partial Sudokus Length:
Empty DataFrame
Columns: [Unnamed: 0, partialsudokus, filledsudokus]
Index: []

In [ ]:
def preprocess_puzzle(puzzle_str):
    """
    Preprocess the input Sudoku puzzle string into a format suitable for the model.
    """
    puzzle_tensor = torch.tensor([int(p) for p in puzzle_str], dtype=torch.float32).reshape(1, 1, 9, 9) / 9 - 0.5
    return puzzle_tensor.to(device)

def predict_test_set(model, test_df):
    """
    Predict solutions for all puzzles in the test DataFrame.
    """
    model.eval()
    predictions = []

    for _, row in test_df.iterrows():
        #print(row)
        puzzle_str = row['partialsudokus']
        with torch.no_grad():
            puzzle_tensor = preprocess_puzzle(puzzle_str)
            output = model(puzzle_tensor)
            solution = output.argmax(dim=1).view(9, 9) + 1  # Convert predictions to 1-based indexing
            predictions.append(solution.cpu().numpy())

    return predictions

In [ ]:
# predict on the entire test set
predicted_solutions = predict_test_set(model, test_sudokus)

In [ ]:
indexes = []
labels= []
#for i,j in enumerate(predicted_solutions_df["predicted_solution"]):
for i,j in enumerate(predicted_solutions):
    preds = j.reshape(9,9)
    for row in range(0,9):
        for col in range(0,9):
            index = str(i)+"_"+str(row)+str(col)
            indexes.append(index)
            labels.append(preds[row,col])

In [ ]:
Test_Predictions =  {"id":indexes , "values":labels}
Test_Predictions = pd.DataFrame(Test_Predictions)
Test_Predictions

             id  values
0          0_00       4
1          0_01       4
2          0_02       2
3          0_03       7
4          0_04       5
...         ...     ...
809995  9999_84       8
809996  9999_85       8
809997  9999_86       3
809998  9999_87       9
809999  9999_88       8

[810000 rows x 2 columns]

In [ ]:
Test_Predictions.to_csv("Submission_Task2.csv", index=False)